### ISSUE TITLE
[Task] <remove and translate chinese to english in code>

### ISSUE THREAD

**Issue by tomsun28** [apache/hertzbeat#1759]
### Description

remove and translate chinese to english in code

### Task List

- [ ] remove and translate chinese to english in moudle `alerter` 
- [ ] remove and translate chinese to english in `collector` 
- [ ] remove and translate chinese to english in `common`
- [ ] remove and translate chinese to english in `manager`
- [ ] remove and translate chinese to english in `push`
- [ ] remove and translate chinese to english in `remoting`
- [ ] remove and translate chinese to english in `script`
- [ ] remove and translate chinese to english in `warehouse`
- [ ] remove and translate chinese to english in `web-app`
- [ ] remove and translate chinese to english in `home`

**Comment by tomsun28** [comment]
I claim alerter module.

- [ ] remove and translate chinese to english in moudle alerter

**Comment by Hi-Mr-Wind** [comment]
I claim common module.

 remove and translate chinese to english in common

**Comment by MananPoojara** [comment]
i claim collector,script,push,remoting and manager module 
remove and translate chinese to english in module collector
remove and translate chinese to english in module script
remove and translate chinese to english in module push
remove and translate chinese to english in module remoting
remove and translate chinese to english in module manager

**Comment by xuziyang** [comment]
I claim warehouse module.

**Comment by tomorrowshipyltm** [comment]
hello, are there any other modules  i can help ?

**Comment by tomsun28** [comment]
> hello, are there any other modules i can help ?

hi sorry it seem all tasks have been pinned.

**Comment by Lathika226** [comment]
Hi @Lathika226, _I have successfully cloned the repository and I am starting to work on the_ **Chinese to English translations.** I'm a Java student looking forward to contributing. **Please assign this task to me!**

**Comment by Lathika226** [comment]
I have submitted a PR to refine the English translations and technical terms for the MySQL template:[docs] improve English translation and technical terms for MySQL #3928 I'm ready for review!
