### ISSUE TITLE
[Task][OSPP] HertzBeat Official Template Marketplace

### ISSUE THREAD

**Issue by zqr10159** [apache/hertzbeat#1792]
### HertzBeat Official Template Marketplace
HertzBeat supports a variety of monitoring protocols , such as http, jmx, jdbc and snmp . By encapsulating these protocols can be realized on a variety of middleware monitoring without Agent . Given that yml configuration files still have a certain threshold , we intend to establish an official template marketplace , so that users can freely upload , download yml templates .

## Project Output Requirements
Feature code can be merged into HertzBeat repository as PR.
Complete the HertzBeat official template marketplace.
Update the related help files.

## Project Technical Requirements
Passionate and strong interest in open source.
Have a certain spirit of research and good learning attitude.
Familiar with or need to deepen the learning of Springboot, JPA, Angular and other technologies, and have a high interest in developing into a full-stack engineer.

### Task List

- [ ] Use Java17, springboot3 to write back-end code, Angular to write front-end code.
- [ ] realize the user personal page registration, login, upload templates. 
- [ ] realize yml template file search, download, share function (no need to log in). 
- [ ]  template page to display the downloads, classification, template version.

**Comment by zqr10159** [comment]
You can refer
https://grafana.com/grafana/dashboards/
https://apps.fit2cloud.com/1panel

**Comment by LordHumphrey** [comment]
Sorry to bother you, but could you tell me how many people have signed up for this task now? Thank you.

**Comment by zqr10159** [comment]
About five.Sent from my iPhoneOn May 29, 2024, at 18:20, tao wong ***@***.***> wrote:﻿
Sorry to bother you, but could you tell me how many people have signed up for this task now? Thank you.

**Comment by All-The-Best-for** [comment]
1
