### ISSUE TITLE
[Task] <title> Write help documents

### ISSUE THREAD

**Issue by TJxiaobao** [apache/hertzbeat#1795]
### Description

We have some help documents for monitoring templates that have not been written, and now we need some volunteers to write the documents.
May refer to：
https://github.com/apache/hertzbeat/tree/master/home/docs/help
https://github.com/apache/hertzbeat/tree/master/home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help
https://github.com/apache/hertzbeat/tree/master/manager/src/main/resources/define

**Note:**  One copy of the help document is required in English and one in Chinese

### Task List

- [ ] almalinux
- [ ] api_code
- [ ] app-cisco_switch
- [ ] app-clickhouse
- [ ] app-coreos
- [ ] app-debian
- [ ] app-dns
- [ ] app-doris_fe
- [ ] app-elasticsearch
- [ ] app-emqx
- [ ] app-euleros
- [ ] app-flink
- [ ] app-freebsd
- [ ] app-ftp
- [ ] app-h3c_switch
- [ ] app-hertzbeat
- [ ] app-hertzbeat_token
- [ ] app-hpe_switch
- [ ] app-huawei_switch
- [ ] app-influxdb_promql
- [ ] app-kafka_promql
- [ ] app-mongodb
- [ ] app-nacos
- [ ] app-nebulaGraph
- [ ] app-opensuse
- [ ] app-prometheus
- [ ] app-push
- [ ] app-redhat
- [ ] app-redis_cluster
- [ ] app-redis_sentinel
- [ ] app-rocketmq
- [ ] app-rockylinux
- [ ] app-springboot3
- [ ] app-storm
- [ ] app-tidb
- [ ] app-tplink_switch
- [ ] app-udp_port
- [ ] app-websocket

**Comment by LiuTianyou** [comment]
Hello, let me write the help documentation for clickhouse monitoring.

**Comment by TJxiaobao** [comment]
Thank you for your contribution.

**Comment by LiuTianyou** [comment]
Hello, I am already familiar with how to add documents. Next, let me add help documents for DNS, elasticsearch, ftp, mongodb, websocket, and prometheus monitoring.

**Comment by zhangshenghang** [comment]
Hello, do doris_fe monitoring documents need to be written? I can complete it.

**Comment by TJxiaobao** [comment]
> Hello, do doris_fe monitoring documents need to be written? I can complete it.

Thank you for your contribution.

**Comment by zuobiao-zhou** [comment]
Please assign `app-springboot3` and `app-udp_port` to me.

**Comment by Alanxtl** [comment]
Hi, I have completed written docs for Huawei Monitoring, Cacos and Tidb.

**Comment by TJxiaobao** [comment]
> Please assign `app-springboot3` and `app-udp_port` to me.

Well, thank you for your contribution.

**Comment by TJxiaobao** [comment]
> Hi, I have completed written docs for Huawei Monitoring, Cacos and Tidb.

If you have finished please mention a pr merge into the master branch, thank you for your contribution.

**Comment by Alanxtl** [comment]
> > Hi, I have completed written docs for Huawei Monitoring, Nacos and Tidb.
> 
> If you have finished please mention a pr merge into the master branch, thank you for your contribution.

They have been merged https://github.com/apache/hertzbeat/pull/1823 and https://github.com/apache/hertzbeat/pull/1813

**Comment by zhangshenghang** [comment]
> > Hello, do doris_fe monitoring documents need to be written? I can complete it.
> 
> Thank you for your contribution.

Hi,Doris FE Chinese and English documentation has been added, and I have submitted a PR.

**Comment by TJxiaobao** [comment]
> > > Hi, I have completed written docs for Huawei Monitoring, Nacos and Tidb.
> > 
> > 
> > If you have finished please mention a pr merge into the master branch, thank you for your contribution.
> 
> They have been merged #1823 and #1813

👍👍👍

**Comment by TJxiaobao** [comment]
> > > Hello, do doris_fe monitoring documents need to be written? I can complete it.
> > 
> > 
> > Thank you for your contribution.
> 
> Hi,Doris FE Chinese and English documentation has been added, and I have submitted a PR.

👍👍👍

**Comment by zhangshenghang** [comment]
Hi, is the debian system monitoring file completed? i can finish it

**Comment by TJxiaobao** [comment]
> debian



> Hi, is the debian system monitoring file completed? i can finish it

Not at the moment, you can try to finish it.

**Comment by TJxiaobao** [comment]
> Hi, is the debian system monitoring file completed? i can finish it

this issue :https://github.com/apache/hertzbeat/issues/1835

**Comment by HeartLinked** [comment]
I can try to complete documents for flink and tplink_switch. Please assign them to me.

**Comment by zhangshenghang** [comment]
Hi,Almalinux can be assigned to me

**Comment by TJxiaobao** [comment]
> Hi,Almalinux can be assigned to me

👍👍👍

**Comment by Thespica** [comment]
Hi, @TJxiaobao , I noticed that [this part of doc](https://hertzbeat.apache.org/zh-cn/docs/community/development#build-hertzbeat-binary-package) is under `zh-cn` but written in `en`.

I can translated it to Chinese if this work is needed.

**Comment by zzzk1** [comment]
pls assigne app-redis_cluster to me ~

**Comment by preetipujari2025** [comment]
Hi, I’m new to the project and would like to work on this documentation task.
Please let me know if I can take this up and if there are specific sections you’d like me to start with.

**Comment by yyyCode** [comment]
Hi, I'd like to contribute the help documentation for the **Fedora CoreOS** (`coreos`) monitoring type, which currently has no help doc in either English or Chinese and is not yet registered in the sidebar.

I'll add:
- `home/docs/help/coreos.md` (EN)
- `home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/coreos.md` (zh-CN)
- register `help/coreos` under the `os` category in `home/sidebars.json`

The doc follows the existing OS SSH monitoring doc format (same as `almalinux`), covering the basic / cpu / memory / disk / interface / disk_free / top_cpu_process / top_mem_process metric sets. Please assign it to me.

**Comment by paultanay** [comment]
Hi, I'd like to help with the documentation for the push style monitor (app-push). I'll add the English doc, Chinese translation, and sidebar entry. Will open the PR shortly!
