### ISSUE TITLE
[Task] Support monitoring of Apache Hbase Master nodes

### ISSUE THREAD

**Issue by zhangshenghang** [apache/hertzbeat#1812]
### Description

Support monitoring of Apache Hbase Master nodes

Recommended monitoring Metrics:

### Task List

- [ ]  Number of abnormal RegionServers
- [ ]  Number of active RegionServers
- [ ] Average cluster load
- [ ] Number of cluster requests
- [ ] Count of Regions in transition
- [ ] Number of Regions with transition time exceeding the threshold
- [ ] Oldest RIT time
- [ ] Number of cluster load balancing occurrences
- [ ] Count of RPC handles

**Comment by zhangshenghang** [comment]
I can do it. Thank you for assigning it to me. Thank you
