### ISSUE TITLE
[Task] <collector support agent ability>

### ISSUE THREAD

**Issue by tomsun28** [apache/hertzbeat#2268]
### Description

now we can deploy collector as a agent in a local machine, but can not run local shell or cmd script in local machine to collect metrics data. 

### Task List

- [ ] design the protocol 
- [ ] support run shell script in local linux machine to collect metrics data.
- [ ] support run cmd bat script in local windows machine to collect metrics data.

**Comment by zuobiao-zhou** [comment]
Please assign it to me.

**Comment by tomsun28** [comment]
hi yes. run shell in linux and run bat cmd in windows not required connect.

**Comment by zhangshenghang** [comment]
> hi yes. run shell in linux and run bat cmd in windows not required connect.

👍🏻👍🏻👍🏻👍🏻  is a good feature
