### ISSUE TITLE
[Task] <Move code from controller to service in module hertzbeat-manager>

### ISSUE THREAD

**Issue by Calvin979** [apache/hertzbeat#2407]
### Description

Move code from controller to service in module `hertzbeat-manager`.
See also: #2373 
As a layer of interaction with front-end, controller should not contain any code logic except param validation.

> Comment down below if you want to claim task.
> eg: I claim xxxController

### Task List

- [ ] org.apache.hertzbeat.manager.controller.CollectorController
- [x] org.apache.hertzbeat.manager.controller.GeneralConfigController
- [x] org.apache.hertzbeat.manager.controller.MonitorsController
- [x] org.apache.hertzbeat.manager.controller.NoticeConfigController
- [x] org.apache.hertzbeat.manager.controller.PluginController
- [x] org.apache.hertzbeat.manager.controller.TagController

**Comment by ceekay47** [comment]
Hi @Calvin979, I would like to contribute. I can look into refactoring CollectorController to get started. Can you please provide some context?

**Comment by pwallk** [comment]
I can finish the rest of the controller

**Comment by Calvin979** [comment]
> Hi @Calvin979, I would like to contribute. I can look into refactoring CollectorController to get started. Can you please provide some context?

Welcome! Maybe you can refer this pr: #2373 
The key is that `the responsibility of Controller` is to validate param only.
There are some controllers contain a lot of codes out of its responsiblity and that's why we wanna refactor them.

**Comment by Calvin979** [comment]
> I can finish the rest of the controller

Welcome! Suggest one pr for one controller only.

**Comment by MRgenial** [comment]
I claim collectorController

**Comment by Calvin979** [comment]
> I claim collectorController

Thanks for your enthusiasm. `CollectorController` has been assigned. You can try to find another issue
