### ISSUE TITLE
[Task] <Move code from controller to service>

### ISSUE THREAD

**Issue by Calvin979** [apache/hertzbeat#2427]
### Description

Move code from controller to service in module `hertzbeat-alerter` and `hertzbeat-warehouse`.
See also: #2373 #2407 
As a layer of interaction with front-end, controller should not contain any code logic except param validation.

> Comment down below if you want to claim task.
> eg: I claim xxxController

### Task List

- [ ] org.apache.hertzbeat.alert.controller.AlertConvergesController
- [ ] org.apache.hertzbeat.alert.controller.AlertDefinesController
- [ ] org.apache.hertzbeat.alert.controller.AlertReportController
- [ ] org.apache.hertzbeat.alert.controller.AlertsController
- [ ] org.apache.hertzbeat.alert.controller.AlertSilencesController
- [ ] org.apache.hertzbeat.warehouse.controller.MetricsDataController

**Comment by pwallk** [comment]
I already have experience with this Task and I can complete these
