### ISSUE TITLE
[Task] Use apache arrow to store metrics data

### ISSUE THREAD

**Issue by tomsun28** [apache/hertzbeat#2825]
### Description

use apache arrow to store metrics data instead of protobuf `Field ValueRow` 
```
    // monitoring collect metric field
    repeated Field fields = 9;
    // monitoring collect metric data, mapping with the fields
    repeated ValueRow values = 10;
```

**Comment by Calvin979** [comment]
Is it a task now? I'm interested in it

**Comment by tomsun28** [comment]
yes welcome. 👍

**Comment by Calvin979** [comment]
> maybe we can use
> 
> ```
>    // collect response data
>     bytes data = 9;
> ```
> 
> to instead of
> 
> ```
>     // monitoring collect metric field
>     repeated Field fields = 9;
>     // monitoring collect metric data, mapping with the fields
>     repeated ValueRow values = 10;
> ```
> 
> in collect_rep.proto
> 
> and then use the apache arrow to construct the metrics data `bytes data = 9`

Thanks for your suggestion, I need to learn `Apache Arrow` first.

**Comment by Calvin979** [comment]
# Todo List
- [ ] Complete comment on new method and class.
- [ ] Delete Field and ValueRow in `collect_rep.proto`.
- [x] Modify collected data in package `hertzbeat-collector`
- [ ] Add JDK options in scripts. See also: https://arrow.apache.org/docs/java/install.html#java-compatibility
- [ ] Change unit case in package `hertzbeat-collector`
- [ ] org.apache.hertzbeat.warehouse.store.history.HistoryDataWriter#saveData
- [ ] org.apache.hertzbeat.warehouse.store.realtime.RealTimeDataWriter#saveData
